### ISSUE TITLE
session.match error

### ISSUE THREAD

**Issue by pedrouops** [kyo-ago/node-hue-remote#2]
dont know if this library is still under development, however i cant put it to work.
after doing: 
   // require('HueRemote'); doesn't work with NodeJs
    var HueRemote = require('../node_modules/node-hue-remote/lib/HueRemote');

    var hue = new HueRemote({
      'account' : {
        'email': 'mail',
        'password': 'pass'
      }
    });
can't call any method from hue variable

**Comment by kyo-ago** [comment]
yes. this library is not under development.

>// require('HueRemote'); doesn't work with NodeJs
fix this issue.

> session.match error
but still throwing this problem.
sorry, this library is deprecated.
(Recommend a fork or another solution)
